"""add auth fields and user email

Revision ID: add_auth_fields
Revises: 143a35ac668d
Create Date: 2026-03-03

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "add_auth_fields"
down_revision: Union[str, None] = "143a35ac668d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Adicionar colunas de autenticação na tabela users
    op.add_column("users", sa.Column("email", sa.String(), nullable=True))
    op.add_column("users", sa.Column("password_hash", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column("is_active", sa.Boolean(), nullable=True, server_default="true"),
    )
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=True))

    # Criar índice único para email
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    # Atualizar registros existentes com valores padrão
    op.execute(
        "UPDATE users SET email = 'user' || id || '@medtutor.local', password_hash = 'temp_hash', created_at = CURRENT_TIMESTAMP WHERE email IS NULL"
    )

    # Tornar colunas não-nulas
    op.alter_column("users", "email", nullable=False)
    op.alter_column("users", "password_hash", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "created_at")
    op.drop_column("users", "is_active")
    op.drop_column("users", "password_hash")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
